### ISSUE TITLE
NoSuchMethodError after entering prompt

### ISSUE THREAD

**Issue by bigbenchrob** [rutvik110/tGPT#1]
Thanks for this cool dart command line app for ChatGPT. Unfortunately, I'm getting the error below after I enter a prompt.

I installed the app and entered my API key when prompted. When I run the command:

`$ ❯ dart run bin/terminalgpt.dart`

I see a welcome message followed by "What would you like to ask tGPT?". When I enter a prompt ("how do i install flutter on Macos") I see:

```
Input:How do I install flutter on Macos

Chat History: 0
✓ Calling OpenAI API... (0.2s)

Error calling the OpenAI API: NoSuchMethodError: The method '[]' was called on null.
Receiver: null
Tried calling: [](0)
```

MacOS Ventura 13.0.1
Dart SDK version: 2.19.2 (stable) (Tue Feb 7 18:37:17 2023 +0000) on "macos_x64"

**Comment by rutvik110** [comment]
hey thanx for submitting the issue. 

I was able to reproduce the issue on my side. On my side it was due to invalid api key. 

I updated some error handling around the code, so actual issues that caused this error should be shown properly now in terminal. Make sure to pull latest updates first which should hightlight your issue in terminal.

**Comment by rutvik110** [comment]
Let me know if that helps, else I'm active rn so you can respond here with your results.

**Comment by rutvik110** [comment]
btw, any suggestions from ur side to improve this would be helpful. I've plans to add search feature to look up previous chat history but not sure if that would be something suited for teminal experience.

**Comment by bigbenchrob** [comment]
Excellent! Got an informative error message (I think I must have gotten the API from a non-paid account):

```
Error occured: Exception: {message: You exceeded your current quota, please check your plan and billing details., 
type: insufficient_quota, param: null, code: null}
```

**Comment by rutvik110** [comment]
Awesome! Glad that helped🙌
